pipeline {

    agent any

    environment {
        IMAGE_NAME = "agentic-rag"
        CONTAINER_NAME = "agentic-rag"
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'

                git branch: 'main',
                    url: 'https://github.com/venkataravindra/agentic-rag.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'

                sh '''
                    docker build -t ${IMAGE_NAME}:latest .
                '''
            }
        }

        stage('Stop Old Container') {
            steps {
                echo 'Stopping old container...'

                sh '''
                    docker stop ${CONTAINER_NAME} || true
                    docker rm ${CONTAINER_NAME} || true
                '''
            }
        }

        stage('Run New Container') {
            steps {

                withCredentials([
                    string(
                        credentialsId: 'anthropic-api-key',
                        variable: 'ANTHROPIC_API_KEY'
                    )
                ]) {

                    sh '''
                        docker run -d \
                            --name ${CONTAINER_NAME} \
                            -p 8000:8000 \
                            -e ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}" \
                            ${IMAGE_NAME}:latest
                    '''
                }
            }
        }

        stage('Verify Application') {
            steps {
                echo 'Checking application...'

                sh '''
                    sleep 10
                    curl -f http://localhost:8000/ || exit 1
                '''
            }
        }
    }

    post {

        success {
            echo 'Agentic RAG deployment successful!'
        }

        failure {
            echo 'Agentic RAG deployment failed!'
        }
    }
}